<?xml version="1.0" encoding="utf-8"?><Database Name="InfiniteDB" Class="MydbmlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-TJJ7D977;Initial Catalog=InfiniteDB;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="Linq_Sql_VS.Properties.Settings" SettingsPropertyName="InfiniteDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblEmployee" Member="tblEmployees">
    <Type Name="tblEmployee">
      <Column Name="EmpId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EmpName" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="Char(7)" CanBeNull="true" />
      <Column Name="Salary" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DeptId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phoneno" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="AnnualSalary" Type="System.Double" DbType="Float" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="tblDepartment_tblEmployee" Member="tblDepartment" ThisKey="DeptId" OtherKey="DeptNum" Type="tblDepartment" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblDepartment" Member="tblDepartments">
    <Type Name="tblDepartment">
      <Column Name="DeptNum" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Deptname" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DeptLocation" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="tblDepartment_tblEmployee" Member="tblEmployees" ThisKey="DeptNum" OtherKey="DeptId" Type="tblEmployee" />
    </Type>
  </Table>
  <Function Name="dbo.sp_getsalary" Method="sp_getsalary">
    <Parameter Name="ename" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="salary" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>